# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-69e7a964-4e37-47eb-aab1-07bc8c991cec";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-69e7a964-4e37-47eb-aab1-07bc8c991cec".device = "/dev/disk/by-uuid/69e7a964-4e37-47eb-aab1-07bc8c991cec";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D21A-E058";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-65a904f2-7e9a-410a-8031-ef7f237f78f4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
